const fs = require('fs');
const missing = {
  "common.select": "Tanlang",
  "common.actions": "Amallar",
  "dashboard.overview": "Umumiy ko'rinish",
  "dashboard.overviewDesc": "Klinika faoliyati bo'yicha tahliliy hisobot",
  "dashboard.doctorDesc": "Shaxsiy statistika va natijalar",
  "dashboard.receptionistDesc": "Bugungi kunlik hisobot",
  "dashboard.newLeads": "YANGI LIDLAR",
  "dashboard.fromAds": "Reklamadan",
  "dashboard.avgCheck": "O'RTACHA CHEK",
  "dashboard.perPatient": "Bemor boshiga",
  "dashboard.unpaid": "To'lanmagan",
  "dashboard.financialFlow": "Moliya oqimi",
  "dashboard.income": "Daromad",
  "dashboard.visits": "Tashriflar",
  "dashboard.active": "faol",
  "dashboard.allOk": "Hammasi joyida",
  "dashboard.pending": "Kutilmoqda",
  "dashboard.selectedPeriod": "TANLANGAN DAVR",
  "dashboard.todayTitleA": "Bugungi",
  "dashboard.todayTitleB": "qabullar",
  "dashboard.count": "ta",
  "dashboard.seeAll": "Barchasi",
  "dashboard.moreAll": "Yana",
  "dashboard.noAppointmentsToday": "Bugun uchun qabullar yo'q",
  "dashboard.colTime": "Vaqt",
  "dashboard.colPatient": "Bemor",
  "dashboard.colDoctor": "Shifokor",
  "dashboard.colService": "Xizmat",
  "dashboard.colStatus": "Status",
  "dashboard.colState": "Holat",
  "dashboard.colActions": "Amallar",
  "dashboard.colDateTime": "Sana/vaqt",
  "dashboard.debtsTitleA": "Kutilayotgan",
  "dashboard.debtsTitleB": "to'lovlar",
  "dashboard.debtsDesc": "Qarzga yozilgan, hali yopilmagan",
  "dashboard.unpaidTitleA": "To'lov",
  "dashboard.unpaidTitleB": "kutayotganlar",
  "dashboard.unpaidDesc": "Tugallangan, to'lov olinmagan",
  "dashboard.recall.titleA": "Nazorat",
  "dashboard.recall.titleB": "tashriflari",
  "dashboard.recall.desc": "Qayta qabulga chaqirish vaqti keldi",
  "dashboard.recall.kindTreatment": "davolanishni davom ettirish",
  "dashboard.recall.kindCheckup": "nazorat ko'rigi",
  "dashboard.recall.overdue": "muddati o'tgan",
  "dashboard.recall.reminded": "eslatma yuborilgan",
  "dashboard.recall.call": "Qo'ng'iroq qilish",
  "dashboard.recall.dismiss": "Bekor qilish",
  "dashboard.recall.less": "Yashirish",
  "dashboard.moveDay": "Boshqa kunga ko'chirish",
  "dashboard.cancel": "Bekor qilish",
  "dashboard.justNow": "Hozirgina",
  "dashboard.recently": "Yaqinda",
  "dashboard.byMonthDays": "Joriy oy kunlari bo'yicha",
  "dashboard.byLast12": "So'nggi 12 oy davomida",
  "dashboard.half": "Yarmi",
  "dashboard.period": "Davr",
  "dashboard.quickPatient": "Bemor",
  "dashboard.quickAppointment": "Qabul",
  "dashboard.quickPayment": "To'lov",
  "header.search": "Bemor yoki shifokor izlash...",
  "app.install": "Ilovani o'rnatish",
  "calendar.title": "Kalendar",
  "calendar.day": "Kun",
  "calendar.week": "Hafta",
  "calendar.newAppointment": "Yangi qabul",
  "calendar.sendReminder": "Eslatma yuborish",
  "calendar.editAppointment": "Qabulni tahrirlash",
  "calendar.appointmentDetails": "Qabul tafsilotlari",
  "calendar.patient": "Bemor",
  "calendar.doctor": "Shifokor",
  "calendar.serviceCategory": "Xizmat toifasi",
  "calendar.allCategories": "Barcha toifalar",
  "calendar.serviceType": "Davolash turi",
  "calendar.duration": "Davomiyligi (daq)",
  "calendar.date": "Sana",
  "calendar.time": "Vaqt",
  "calendar.notes": "Eslatmalar",
  "calendar.book": "Band qilish",
  "calendar.sendMessage": "Xabar yuborish",
  "calendar.messageType": "Xabar turi",
  "calendar.customMessage": "Shaxsiy xabar",
  "calendar.tomorrowAppointment": "Ertangi qabul",
  "calendar.reminder": "Eslatma",
  "calendar.messageText": "Xabar matni",
  "calendar.noShow": "Kelmadi",
  "calendar.complete": "Tugatish",
  "calendar.days.sun": "Yak",
  "calendar.days.mon": "Dush",
  "calendar.days.tue": "Sesh",
  "calendar.days.wed": "Chor",
  "calendar.days.thu": "Pay",
  "calendar.days.fri": "Jum",
  "calendar.days.sat": "Shan",
  "leads.title": "Lidlar Voronkasi",
  "leads.subtitle": "Potensial mijozlar bilan ishlash",
  "leads.connectFb": "Facebook ulash",
  "leads.newLead": "Yangi Lid",
  "leads.search": "Izlash...",
  "leads.empty": "Bo'sh",
  "leads.source": "Manba",
  "leads.service": "Xizmat",
  "leads.stages.new": "Yangi",
  "leads.stages.contacted": "Bog'lanildi",
  "leads.stages.thinking": "O'ylanmoqda",
  "leads.stages.booked": "Yozilgan",
  "leads.stages.cancelled": "Rad etildi",
  "finance.title": "Moliya",
  "finance.subtitle": "Daromad, xarajat va yo'qotishlar tahlili",
  "finance.todayIncome": "Bugungi daromad ko'rsatkichi",
  "finance.startDate": "Boshlanish sanasi",
  "finance.endDate": "Tugash sanasi",
  "finance.exportCsv": "Excel",
  "finance.totalIncome": "Umumiy Daromad",
  "finance.todayIncomeCard": "Bugungi daromad",
  "finance.selectedPeriod": "Tanlangan davr uchun",
  "finance.allTime": "Barcha vaqt uchun",
  "finance.debt": "Qarzdorlik",
  "finance.avgCheck": "O'rtacha Chek",
  "finance.techCosts": "Laboratoriya xarajatlari",
  "finance.doctorSalary": "Shifokorlar ulushi (hisoblangan)",
  "finance.netProfit": "Sof Foyda",
  "finance.lossAnalysis": "Yo'qotishlar Tahlili (Kelmadi)",
  "finance.lostRevenue": "Yo'qotilgan Daromad",
  "finance.lossDesc": "Tanlangan davrda kelmagan bemorlar sababli yo'qotishlar.",
  "finance.totalNoShow": "Jami \"Kelmadi\"",
  "finance.uniqueNoShow": "noyob bemor",
  "finance.recoveredPatients": "Qaytarilgan Mijozlar",
  "finance.recoveredDesc": "\"Kelmadi\" deb belgilanib, keyinroq qaytgan bemorlar.",
  "finance.lostCustomers": "Yo'qotildi",
  "finance.paymentMethods": "To'lov Usullari",
  "finance.debtors": "Qarzdorlar",
  "finance.daysLate": "kun kechikkan",
  "finance.viewAll": "Barchasini ko'rish",
  "finance.transactions": "To'lovlar",
  "finance.expenses": "Xarajatlar",
  "finance.table.date": "Sana",
  "finance.table.patient": "Bemor",
  "finance.table.doctor": "Shifokor",
  "finance.table.service": "Xizmat",
  "finance.table.method": "Usul",
  "finance.table.amount": "Summa",
  "finance.table.discount": "Chegirma",
  "finance.table.status": "Status",
  "finance.methods.cash": "Naqd",
  "finance.methods.card": "Karta",
  "finance.methods.insurance": "Sug'urta",
  "finance.methods.balance": "Balansdan (Avans)",
  "leads.addLeadModal.title": "Yangi lid qo'shish",
  "leads.addLeadModal.name": "Mijoz ismi",
  "leads.addLeadModal.phone": "Telefon raqami",
  "leads.addLeadModal.service": "Qiziqtirayotgan xizmat (ixtiyoriy)",
  "leads.addLeadModal.servicePlaceholder": "Masalan: Implant, Breket",
  "leads.addLeadModal.source": "Murojaat manbasi",
  "leads.addLeadModal.notes": "Qo'shimcha izoh",
  "leads.addLeadModal.cancel": "Bekor qilish",
  "leads.addLeadModal.save": "Saqlash",
  "leads.convertModal.title": "Bemorga aylantirish",
  "leads.convertModal.subtitle": "Mijozni tizimga qo'shish va qabulga yozish",
  "leads.convertModal.selectDoctor": "Shifokorni tanlang",
  "leads.convertModal.date": "Sana",
  "leads.convertModal.time": "Vaqt",
  "leads.convertModal.category": "Xizmat toifasi",
  "leads.convertModal.allCategories": "Barcha toifalar",
  "leads.convertModal.procedure": "Jarayon turi",
  "leads.convertModal.duration": "Davomiyligi (daq)",
  "leads.convertModal.cancel": "Bekor qilish",
  "leads.convertModal.convert": "Bemorga aylantirish",
  "leads.fbModal.title": "Facebook sahifasini tanlang",
  "leads.fbModal.subtitle": "Lidlarni olish uchun sahifani ulang",
  "leads.fbModal.noPages": "Sahifalar topilmadi",
  "leads.fbModal.close": "Yopish",
  "leads.alerts.selectDoctor": "Iltimos, shifokorni tanlang!",
  "leads.alerts.fbFetchError": "Facebook sahifalarini yuklashda xatolik",
  "leads.alerts.fbConnectError": "Facebook'ga ulanishda xatolik",
  "leads.alerts.fbConfigError": "Klinika ID topilmadi. Iltimos, tizimga qayta kiring.",
  "leads.alerts.fbSuccess": "Sahifa muvaffaqiyatli ulandi!",
  "leads.alerts.fbDisconnectConfirm": "Facebook'ni uzishga ishonchingiz komilmi?",
  "leads.success.connectedTitle": "Muvaffaqiyatli ulandi!",
  "leads.success.connectedDesc": "Facebook hisobingiz ulandi. Bu oyna hozir yopiladi...",
  "leads.sources.instagram": "Instagram",
  "leads.sources.telegram": "Telegram",
  "leads.sources.recommendation": "Tavsiya",
  "leads.sources.banner": "Banner",
  "leads.sources.other": "Boshqa",
  "patients.alerts.duplicateName": "Bunday ism va familiyali bemor mavjud! Iltimos, ajratish uchun sharifi yoki tug'ilgan yilini qo'shing (masalan: Aliyev Toshkent 1990).",
  "leads.detailsModal.title": "Lid haqida batafsil ma'lumot",
  "leads.detailsModal.created": "Yaratilgan sana",
  "leads.detailsModal.close": "Yopish",
  "finance.debtorsModal.filterByDoctor": "Shifokor bo'yicha filtr",
  "finance.debtorsModal.allDoctors": "Barcha shifokorlar",
  "finance.debtorsModal.filteredDebt": "Filtrlangan qarz",
  "finance.debtorsModal.debtorsCount": "qarzdor",
  "common.days.0": "Yak",
  "common.days.1": "Dush",
  "common.days.2": "Sesh",
  "common.days.3": "Chor",
  "common.days.4": "Pay",
  "common.days.5": "Jum",
  "common.days.6": "Shan",
  "calendar.alerts.noDoctorSys": "Tizimda shifokor yo'q! Iltimos, 'Xodimlar' bo'limiga o'tib, kamida bitta profil yarating.",
  "calendar.alerts.tgNotLinked": "Bemor Telegram botga ulanmagan. Iltimos, bot havolasini yuboring.",
  "calendar.alerts.msgError": "Xabar yuborishda xatolik yuz berdi.",
  "calendar.alerts.enterName": "Iltimos, bemorning ism-familiyasini kiriting!",
  "calendar.labels.goToProfile": "Bemor profiliga o'tish",
  "calendar.labels.editAppt": "Qabulni tahrirlash",
  "calendar.alerts.patientNotFound": "Bemor topilmadi.",
  "cashbook.advanceDeducted": "Avansdan ushlandi",
  "cashbook.cashRegister": "Naqd pul hisobi",
  "cashbook.noCashMovement": "Bu kunda naqd pul harakati bo'lmagan.",
  "cashbook.shouldBeInRegister": "Kassada bo'lishi kerak",
  "cashbook.uzs": "UZS",
  "cashbook.cashierCounted": "Kassir hisobladi",
  "cashbook.difference": "Farq",
  "cashbook.closeDay": "Kunni yopish",
  "cashbook.dayClosed": "Kun yopilgan",
  "cashbook.counted": "Hisoblangan",
  "cashbook.byAccount": "Hisob bo'yicha",
  "cashbook.recount": "Qayta hisoblash",
  "cashbook.reopen": "Qayta ochish",
  "cashbook.title": "Kassa",
  "cashbook.subtitle": "Kassadagi real kirim va chiqimlar",
  "cashbook.btnPayment": "To'lov",
  "cashbook.btnExpense": "Xarajat",
  "cashbook.btnEncashment": "Inkassatsiya",
  "cashbook.btnRefund": "Qaytarish",
  "cashbook.btnToday": "Bugun",
  "cashbook.btnExcel": "Excel",
  "cashbook.noPayments": "Bu kunda to'lovlar qayd etilmagan",
  "cashbook.thPatient": "Bemor",
  "cashbook.thTime": "Vaqt",
  "cashbook.thMethod": "Usul",
  "cashbook.total": "JAMI",
  "cashbook.dayPayments": "Kunlik to'lovlar",
  "cashbook.noPaymentsDay": "Bu kunda to'lovlar yo'q",
  "cashbook.unpaid": "To'lanmagan",
  "cashbook.allPaid": "Barchadan pul olingan",
  "cashbook.writtenToDebt": "Qarzga yozilgan",
  "cashbook.visitFinishedNoPay": "Qabul tugallangan, to'lov yo'q",
  "cashbook.pay": "To'lash",
  "cashbook.expenses": "Xarajatlar",
  "cashbook.noExpenses": "Bu kunda xarajatlar yo'q",
  "cashbook.cashMovements": "Kassa harakatlari",
  "cashbook.noMovements": "Kassadan pul olinmagan va kiritilmagan",
  "cashbook.auditTrail": "O'zgarishlar jurnali",
  "cashbook.loading": "Yuklanmoqda...",
  "cashbook.noChanges": "Bu kunda o'zgarishlar bo'lmagan",
  "cashbook.dailyBook": "Kunlik jurnal",
  "cashbook.thDay": "Kun",
  "cashbook.thCash": "Naqd",
  "cashbook.thCard": "Karta",
  "cashbook.thTotal": "Jami",
  "cashbook.thRemains": "Kassada qoldi",
  "cashbook.thStatus": "Status",
  "cashbook.whereFrom": "Qayerdan to'landi",
  "cashbook.deductHint": "Naqd pul tanlanganda kassadagi summa kamayadi. Qolgani hisobdan yechiladi.",
  "cashbook.cancel": "Bekor qilish",
  "cashbook.nowShouldBe": "Hozir kassada bo'lishi kerak",
  "cashbook.paymentMethod": "To'lov usuli",
  "cashbook.dayClosedWarn": "Bu kun yopilgan. O'zgartirilsa, kassadagi summa o'zgaradi va tarixda qoladi.",
  "cashbook.balanceStart": "Kun boshidagi qoldiq",
  "cashbook.cashIn": "Naqd pul kirimi",
  "cashbook.cashOut": "Naqd pul chiqimi",
  "cashbook.accountedCash": "Kassada hisob bo'yicha",
  "cashbook.compareCard": "Naqdsiz to'lovlarni solishtirish",
  "cashbook.dayStart": "Kun boshida",
  "cashbook.cashInStr": "Naqd tushum",
  "cashbook.encashIn": "Kassaga solindi",
  "cashbook.cashOutStr": "Naqd xarajat",
  "cashbook.refund": "Qaytarish",
  "cashbook.encashment": "Inkassatsiya",
  "cashbook.income": "Kirim",
  "cashbook.outcome": "Chiqim",
  "cashbook.addedToAccount": "Hisobga qo'shildi",
  "cashbook.takenFromCash": "Kassadan olindi",
  "cashbook.patientRefund": "Bemorga qaytarish",
  "cashbook.prevDay": "Oldingi kun",
  "cashbook.nextDay": "Keyingi kun",
  "cashbook.prevMonth": "Oldingi oy",
  "cashbook.nextMonth": "Keyingi oy",
  "cashbook.correction": "Tuzatish",
  "cashbook.delete": "O'chirish",
  "cashbook.category": "Toifa",
  "cashbook.saving": "Saqlanmoqda...",
  "cashbook.save": "Saqlash",
  "cashbook.notSelected": "Tanlanmagan",
  "cashbook.whoReceived": "Kimga berildi",
  "cashbook.whyRefunded": "Qaytarish sababi"
};

let transContent = fs.readFileSync('i18n/translations.ts', 'utf8');
let entries = [];
for (const [key, value] of Object.entries(missing)) {
    entries.push(`    '${key}': "${value}",`);
}

const ruIndex = transContent.indexOf('  ru: {');
if (ruIndex !== -1) {
    const lastCommaUz = transContent.lastIndexOf('  },', ruIndex);
    if (lastCommaUz !== -1) {
        const injectedUz = '\n    // --- MISSING TRANSLATIONS ---\n' + entries.join('\n') + '\n';
        transContent = transContent.slice(0, lastCommaUz) + injectedUz + transContent.slice(lastCommaUz);
    }
}

fs.writeFileSync('i18n/translations.ts', transContent, 'utf8');
console.log('Successfully injected missing translations!');
