// DHP (Raqamli sog'liqni saqlash platformasi) lug'atlari.
// Manba: https://dhp.uz/fhir/core — states-cs (viloyat), regions-cs (tuman, SOATO),
// dmed-specialties-cs (mutaxassislik). Tuman kodining birinchi 4 raqami = viloyat kodi.
// Qo'lda tahrirlamang: IG yangilansa shu ro'yxat qayta olinadi.

export interface DhpCode { code: string; uz: string; ru: string }

export const DHP_STATES: DhpCode[] = [
  { code: "1703", uz: "Andijon viloyati", ru: "Андижанская область" },
  { code: "1706", uz: "Buxoro viloyati", ru: "Бухарская область" },
  { code: "1708", uz: "Jizzax viloyati", ru: "Джизакская область" },
  { code: "1710", uz: "Qashqadaryo viloyati", ru: "Кашкадарьинская область" },
  { code: "1712", uz: "Navoiy viloyati", ru: "Навоийская область" },
  { code: "1714", uz: "Namangan viloyati", ru: "Наманганская область" },
  { code: "1718", uz: "Samarqand viloyati", ru: "Самаркандская область" },
  { code: "1722", uz: "Surxondaryo viloyati", ru: "Сурхандарьинская область" },
  { code: "1724", uz: "Sirdaryo viloyati", ru: "Сырдарьинская область" },
  { code: "1726", uz: "Toshkent shahar", ru: "Город Ташкент" },
  { code: "1727", uz: "Toshkent viloyati", ru: "Ташкентская область" },
  { code: "1730", uz: "Farg'ona viloyati", ru: "Ферганская область" },
  { code: "1733", uz: "Xorazm viloyati", ru: "Хорезмская область" },
  { code: "1735", uz: "Qoraqalpog'iston Respublikasi", ru: "Республика Каракалпакстан" },
];

export const DHP_DISTRICTS: DhpCode[] = [
  { code: "1703202", uz: "Oltinko'l tumani", ru: "Алтынкульский район" },
  { code: "1703203", uz: "Andijon tumani", ru: "Андижанский район" },
  { code: "1703206", uz: "Baliqchi tumani", ru: "Балыкчинский район" },
  { code: "1703209", uz: "Bo'ston tumani", ru: "Бостонский район" },
  { code: "1703210", uz: "Buloqboshi tumani", ru: "Булокбошинский район" },
  { code: "1703211", uz: "Jalaquduq tumani", ru: "Джалакудукский район" },
  { code: "1703214", uz: "Izboskan tumani", ru: "Избосканский район" },
  { code: "1703217", uz: "Ulug'nor tumani", ru: "Улугнорский район" },
  { code: "1703220", uz: "Qo'rg'ontepa tumani", ru: "Коргонтепинский район" },
  { code: "1703224", uz: "Asaka tumani", ru: "Асакинский район" },
  { code: "1703227", uz: "Marhamat tumani", ru: "Мархаматский район" },
  { code: "1703230", uz: "Shahrixon tumani", ru: "Шахриханский район" },
  { code: "1703232", uz: "Paxtaobod tumani", ru: "Пахтаабадский район" },
  { code: "1703236", uz: "Xo'jaobod tumani", ru: "Ходжаабадский район" },
  { code: "1703401", uz: "Andijon shahri", ru: "город Андижан" },
  { code: "1703408", uz: "Xonobod shahri", ru: "город Хонобад" },
  { code: "1706204", uz: "Olot tumani", ru: "Олотский район" },
  { code: "1706207", uz: "Buxoro tumani", ru: "Бухарский район" },
  { code: "1706212", uz: "Vobkent tumani", ru: "Вобкентский район" },
  { code: "1706215", uz: "G'ijduvon tumani", ru: "Гиждувонский район" },
  { code: "1706219", uz: "Kogon tumani", ru: "Когонский район" },
  { code: "1706230", uz: "Qorako'l tumani", ru: "Каракольский район" },
  { code: "1706232", uz: "Qorovulbozor tumani", ru: "Гаровулбазарский район" },
  { code: "1706240", uz: "Peshku tumani", ru: "Пешкунский район" },
  { code: "1706242", uz: "Romitan tumani", ru: "Ромитанский район" },
  { code: "1706246", uz: "Jondor tumani", ru: "Джондорский район" },
  { code: "1706258", uz: "Shofirkon tumani", ru: "Шофирконский район" },
  { code: "1706401", uz: "Buxoro shahri", ru: "город Бухара" },
  { code: "1706403", uz: "Kogon shahri", ru: "город Каган" },
  { code: "1708201", uz: "Arnasoy tumani", ru: "Арнасойский район" },
  { code: "1708204", uz: "Baxmal tumani", ru: "Бахмальский район" },
  { code: "1708209", uz: "G'allaorol tumani", ru: "Галлаорольский район" },
  { code: "1708212", uz: "Sharof Rashidov tumani", ru: "Шароф Рашидовский район" },
  { code: "1708215", uz: "Do'stlik tumani", ru: "Дустликский район" },
  { code: "1708218", uz: "Zomin tumani", ru: "Зоминский район" },
  { code: "1708220", uz: "Zarbdor tumani", ru: "Зарбдорский район" },
  { code: "1708223", uz: "Mirzacho'l tumani", ru: "Мирзачольский район" },
  { code: "1708225", uz: "Zafarobod tumani", ru: "Зафарабадский район" },
  { code: "1708228", uz: "Paxtakor tumani", ru: "Пахтакорский район" },
  { code: "1708235", uz: "Forish tumani", ru: "Форишский район" },
  { code: "1708237", uz: "Yangiobod tumani", ru: "Янгиабадский район" },
  { code: "1708401", uz: "Jizzax shahri", ru: "город Джизак" },
  { code: "1710207", uz: "G'uzor tumani", ru: "Гузорский район" },
  { code: "1710212", uz: "Dehqonobod tumani", ru: "Дехканабадский район" },
  { code: "1710220", uz: "Qamashi tumani", ru: "Камашинский район" },
  { code: "1710224", uz: "Qarshi tumani", ru: "Каршинский район" },
  { code: "1710229", uz: "Koson tumani", ru: "Косонский район" },
  { code: "1710232", uz: "Kitob tumani", ru: "Китобский район" },
  { code: "1710233", uz: "Mirishkor tumani", ru: "Миришкорский район" },
  { code: "1710234", uz: "Muborak tumani", ru: "Муборакский район" },
  { code: "1710235", uz: "Nishon tumani", ru: "Нишонский район" },
  { code: "1710237", uz: "Kasbi tumani", ru: "Касбийский район" },
  { code: "1710240", uz: "Ko‘kdala tumani", ru: "Кокдалинский район" },
  { code: "1710242", uz: "Chiroqchi tumani", ru: "Чирокчинский район" },
  { code: "1710245", uz: "Shahrisabz tumani", ru: "Шахрисабзский район" },
  { code: "1710250", uz: "Yakkabog' tumani", ru: "Яккабогский район" },
  { code: "1710401", uz: "Qarshi shahri", ru: "город Карши" },
  { code: "1710405", uz: "Shahrisabz shahri", ru: "город Шахрисабз" },
  { code: "1712211", uz: "Konimex tumani", ru: "Конимехский район" },
  { code: "1712216", uz: "Qiziltepa tumani", ru: "Кизилтепинский район" },
  { code: "1712230", uz: "Navbahor tumani", ru: "Навбахорский район" },
  { code: "1712234", uz: "Karmana tumani", ru: "Карманинский район" },
  { code: "1712238", uz: "Nurota tumani", ru: "Нуратинский район" },
  { code: "1712244", uz: "Tomdi tumani", ru: "Томдинский район" },
  { code: "1712248", uz: "Uchquduq tumani", ru: "Учкудукский район" },
  { code: "1712251", uz: "Xatirchi tumani", ru: "Хатырчинский район" },
  { code: "1712401", uz: "Navoiy shahri", ru: "город Навои" },
  { code: "1712408", uz: "Zarafshon shahri", ru: "город Заравшан" },
  { code: "1712412", uz: "G'ozg'on shahri", ru: "город Гозган" },
  { code: "1714204", uz: "Mingbuloq tumani", ru: "Мингбулокский район" },
  { code: "1714207", uz: "Kosonsoy tumani", ru: "Косонсойский район" },
  { code: "1714212", uz: "Namangan tumani", ru: "Наманганский район" },
  { code: "1714216", uz: "Norin tumani", ru: "Норинский район" },
  { code: "1714219", uz: "Pop tumani", ru: "Папский район" },
  { code: "1714224", uz: "To'raqo'rg'on tumani", ru: "Туракурганский район" },
  { code: "1714229", uz: "Uychi tumani", ru: "Уйчинский район" },
  { code: "1714234", uz: "Uchqo'rg'on tumani", ru: "Учкурганский район" },
  { code: "1714236", uz: "Chortoq tumani", ru: "Чортокский район" },
  { code: "1714237", uz: "Chust tumani", ru: "Чустский район" },
  { code: "1714242", uz: "Yangiqo'rg'on tumani", ru: "Янгикурганский район" },
  { code: "1714401", uz: "Namangan shahri", ru: "город Наманган" },
  { code: "1718203", uz: "Oqdaryo tumani", ru: "Окдарьинский район" },
  { code: "1718206", uz: "Bulung'ur tumani", ru: "Булунгурский район" },
  { code: "1718209", uz: "Jomboy tumani", ru: "Джомбойский район" },
  { code: "1718212", uz: "Ishtixon tumani", ru: "Иштиханский район" },
  { code: "1718215", uz: "Kattaqo'rg'on tumani", ru: "Каттакурганский район" },
  { code: "1718216", uz: "Qo'shrabot tumani", ru: "Кошработский район" },
  { code: "1718218", uz: "Narpay tumani", ru: "Нарпайский район" },
  { code: "1718224", uz: "Payariq tumani", ru: "Паярикский район" },
  { code: "1718227", uz: "Pastdarg'om tumani", ru: "Пастдаргомский район" },
  { code: "1718230", uz: "Paxtachi tumani", ru: "Пахтачинский район" },
  { code: "1718233", uz: "Samarqand tumani", ru: "Самаркандская область" },
  { code: "1718235", uz: "Nurobod tumani", ru: "Нуробадский район" },
  { code: "1718236", uz: "Urgut tumani", ru: "Ургутский район" },
  { code: "1718238", uz: "Toyloq tumani", ru: "Тойлакский район" },
  { code: "1718401", uz: "Samarqand shahri", ru: "город Самарканд" },
  { code: "1718406", uz: "Kattaqo'rg'on shahri", ru: "город Каттакурган" },
  { code: "1722201", uz: "Oltinsoy tumani", ru: "Олтинсойский район" },
  { code: "1722202", uz: "Angor tumani", ru: "Ангорский район" },
  { code: "1722203", uz: "Bandixon tumani", ru: "Бандихонский район" },
  { code: "1722204", uz: "Boysun tumani", ru: "Байсунский район" },
  { code: "1722207", uz: "Muzrabot tumani", ru: "Музработский район" },
  { code: "1722210", uz: "Denov tumani", ru: "Деновский район" },
  { code: "1722212", uz: "Jarqo'rg'on tumani", ru: "Жаркурганский район" },
  { code: "1722214", uz: "Qumqo'rg'on tumani", ru: "Кумкурганский район" },
  { code: "1722215", uz: "Qiziriq tumani", ru: "Кизирикский район" },
  { code: "1722217", uz: "Sariosiyo tumani", ru: "Сариосийский район" },
  { code: "1722220", uz: "Termiz tumani", ru: "Термезский район" },
  { code: "1722221", uz: "Uzun tumani", ru: "Узунский район" },
  { code: "1722223", uz: "Sherobod tumani", ru: "Шерабадский район" },
  { code: "1722226", uz: "Sho'rchi tumani", ru: "Шорчинский район" },
  { code: "1722401", uz: "Termiz shahri", ru: "город Термез" },
  { code: "1724206", uz: "Oqoltin tumani", ru: "Околтинский район" },
  { code: "1724212", uz: "Boyovut tumani", ru: "Бойовутский район" },
  { code: "1724216", uz: "Sayxunobod tumani", ru: "Сайхунабадский район" },
  { code: "1724220", uz: "Guliston tumani", ru: "Гулистонский район" },
  { code: "1724226", uz: "Sardoba tumani", ru: "Сардобинский район" },
  { code: "1724228", uz: "Mirzaobod tumani", ru: "Мирзаабадский район" },
  { code: "1724231", uz: "Sirdaryo tumani", ru: "Сырдарьинский район" },
  { code: "1724235", uz: "Xovos tumani", ru: "Ховосский район" },
  { code: "1724401", uz: "Guliston shahri", ru: "город Гулистан" },
  { code: "1724410", uz: "Shirin shahri", ru: "город Ширин" },
  { code: "1724413", uz: "Yangiyer shahri", ru: "город Янгиер" },
  { code: "1726262", uz: "Uchtepa tumani", ru: "Учтепинский район" },
  { code: "1726264", uz: "Bektemir tumani", ru: "Бектемирский район" },
  { code: "1726266", uz: "Yunusobod tumani", ru: "Юнусабадский район" },
  { code: "1726269", uz: "Mirzo Ulug'bek tumani", ru: "Мирзо-Улугбекский район" },
  { code: "1726273", uz: "Mirobod tumani", ru: "Мирабадский район" },
  { code: "1726277", uz: "Shayxontohur tumani", ru: "Шайхонтохурский район" },
  { code: "1726280", uz: "Olmazor tumani", ru: "Алмазарский район" },
  { code: "1726283", uz: "Sergeli tumani", ru: "Сергелийский район" },
  { code: "1726287", uz: "Yakkasaroy tumani", ru: "Яккасарайский район" },
  { code: "1726290", uz: "Yashnobod tumani", ru: "Яшнабадский район" },
  { code: "1726292", uz: "Yangihayot tumani", ru: "Янгихайотский район" },
  { code: "1726294", uz: "Chilonzor tumani", ru: "Чиланзарский район" },
  { code: "1727206", uz: "Oqqo'rg'on tumani", ru: "Оккурганский район" },
  { code: "1727212", uz: "Ohangaron tumani", ru: "Ахангаронский район" },
  { code: "1727220", uz: "Bekobod tumani", ru: "Бекобадский район" },
  { code: "1727224", uz: "Bo'stonliq tumani", ru: "Бостонликский район" },
  { code: "1727228", uz: "Bo'ka tumani", ru: "Букинский район" },
  { code: "1727233", uz: "Quyi Chirchiq tumani", ru: "Куйи-Чирчикский район" },
  { code: "1727237", uz: "Zangiota tumani", ru: "Зангиотский район" },
  { code: "1727239", uz: "Yuqori Chirchiq tumani", ru: "Юкори Чирчикский район" },
  { code: "1727248", uz: "Qibray tumani", ru: "Кибрайский район" },
  { code: "1727249", uz: "Parkent tumani", ru: "Паркентский район" },
  { code: "1727250", uz: "Piskent tumani", ru: "Пскентский район" },
  { code: "1727253", uz: "O'rta Chirchiq tumani", ru: "Урта Чирчикский район" },
  { code: "1727256", uz: "Chinoz tumani", ru: "Чиназский район" },
  { code: "1727259", uz: "Yangiyo'l tumani", ru: "Янгиюльский район" },
  { code: "1727265", uz: "Toshkent tumani", ru: "Ташкентский район" },
  { code: "1727401", uz: "Nurafshon shahri", ru: "город Нурафшон" },
  { code: "1727404", uz: "Olmaliq shahri", ru: "город Алмалык" },
  { code: "1727407", uz: "Angren shahri", ru: "город Ангрен" },
  { code: "1727413", uz: "Bekobod shahri", ru: "город Бекабад" },
  { code: "1727415", uz: "Ohangaron shahri", ru: "город Ахангаран" },
  { code: "1727419", uz: "Chirchiq shahri", ru: "город Чирчик" },
  { code: "1727424", uz: "Yangiyo'l shahri", ru: "город Янгиюль" },
  { code: "1730203", uz: "Oltiariq tumani", ru: "Олтиарикский район" },
  { code: "1730206", uz: "Qo'shtepa tumani", ru: "Коштепинский район" },
  { code: "1730209", uz: "Bag'dod tumani", ru: "Багдадский район" },
  { code: "1730212", uz: "Buvayda tumani", ru: "Бувайдинский район" },
  { code: "1730215", uz: "Beshariq tumani", ru: "Бешарикский район" },
  { code: "1730218", uz: "Quva tumani", ru: "Кувинский район" },
  { code: "1730221", uz: "Uchko'prik tumani", ru: "Учкоприкский район" },
  { code: "1730224", uz: "Rishton tumani", ru: "Риштонский район" },
  { code: "1730226", uz: "So'x tumani", ru: "Сох район" },
  { code: "1730227", uz: "Toshloq tumani", ru: "Ташлокский район" },
  { code: "1730230", uz: "O'zbekiston tumani", ru: "Узбекистанский район" },
  { code: "1730233", uz: "Farg'ona tumani", ru: "Ферганский район" },
  { code: "1730236", uz: "Dang'ara tumani", ru: "Дангаринский район" },
  { code: "1730238", uz: "Furqat tumani", ru: "Фуркатский район" },
  { code: "1730242", uz: "Yozyovon tumani", ru: "Езёванский район" },
  { code: "1730401", uz: "Farg'ona shahri", ru: "город Фергана" },
  { code: "1730405", uz: "Qo'qon shahri", ru: "город Кокон" },
  { code: "1730408", uz: "Quvasoy shahri", ru: "город Кувасай" },
  { code: "1730412", uz: "Marg'ilon shahri", ru: "город Маргилан" },
  { code: "1733204", uz: "Bog'ot tumani", ru: "Боготский район" },
  { code: "1733208", uz: "Gurlan tumani", ru: "Гурланский район" },
  { code: "1733212", uz: "Qo'shko'pir tumani", ru: "Кошкопирский район" },
  { code: "1733217", uz: "Urganch tumani", ru: "Ургенчский район" },
  { code: "1733220", uz: "Hazorasp tumani", ru: "Азораспский район" },
  { code: "1733221", uz: "Tuproqqal'a tumani", ru: "Тупроккалинский район" },
  { code: "1733223", uz: "Xonqa tumani", ru: "Хонкинский район" },
  { code: "1733226", uz: "Xiva tumani", ru: "Хивинский район" },
  { code: "1733230", uz: "Shovot tumani", ru: "Шовотский район" },
  { code: "1733233", uz: "Yangiariq tumani", ru: "Янгиарикский район" },
  { code: "1733236", uz: "Yangibozor tumani", ru: "Янгибазорский район" },
  { code: "1733401", uz: "Urganch shahri", ru: "город Ургенч" },
  { code: "1733406", uz: "Xiva shahri", ru: "город Хива" },
  { code: "1735204", uz: "Amudaryo tumani", ru: "Амударьинский район" },
  { code: "1735207", uz: "Beruniy tumani", ru: "Берунийский район" },
  { code: "1735209", uz: "Bo'zatov tumani", ru: "Бозатовский район" },
  { code: "1735211", uz: "Qorao'zak tumani", ru: "Караозакский район" },
  { code: "1735212", uz: "Kegeyli tumani", ru: "Кегейлинский район" },
  { code: "1735215", uz: "Qo'ng'irot tumani", ru: "Конгиротский район" },
  { code: "1735218", uz: "Qonliko'l tumani", ru: "Конликольский район" },
  { code: "1735222", uz: "Mo'ynoq tumani", ru: "Муйнакский район" },
  { code: "1735225", uz: "Nukus tumani", ru: "Нукусский район" },
  { code: "1735228", uz: "Taxiatosh tumani", ru: "Таксиаташский район" },
  { code: "1735230", uz: "Taxtako'pir tumani", ru: "Тахткопирский район" },
  { code: "1735233", uz: "To'rtko'l tumani", ru: "Торткульский район" },
  { code: "1735236", uz: "Xo'jayli tumani", ru: "Ходжалинский район" },
  { code: "1735240", uz: "Chimboy tumani", ru: "Чимбойский район" },
  { code: "1735243", uz: "Shumanay tumani", ru: "Шуманайский район" },
  { code: "1735250", uz: "Ellikqal’a tumani", ru: "Элликкалинский район" },
  { code: "1735401", uz: "Nukus shahri", ru: "город Нукус" },
];

/**
 * Stomatologiyaga tegishli DHP mutaxassislik kodlari —
 * PractitionerRole.specialty uchun profession-specialization-cs (SNOMED CT asosida).
 * Lavozim kodi (position-and-profession-cs) backendda shu koddan chiqariladi:
 * backend/dhp/codes.ts DENTAL_SPECIALTIES — ikkalasi bir xil bo'lishi kerak.
 */
export const DHP_DENTAL_SPECIALTIES: DhpCode[] = [
  { code: "408444009", uz: "Umumiy stomatologiya amaliyoti", ru: "Общая стоматологическая практика" },
  { code: "394606000", uz: "Restorativ (terapevtik) stomatologiya", ru: "Терапевтическая (восстановительная) стоматология" },
  { code: "408441001", uz: "Endodontiya", ru: "Эндодонтия" },
  { code: "408461007", uz: "Periodontologiya", ru: "Пародонтология" },
  { code: "394605001", uz: "Og'iz bo'shlig'i jarrohligi", ru: "Хирургия полости рта" },
  { code: "408465003", uz: "Og'iz-jag' jarrohligi", ru: "Челюстно-лицевая хирургия" },
  { code: "394608004", uz: "Ortodontiya", ru: "Ортодонтия" },
  { code: "408460008", uz: "Protezlash (ortopedik stomatologiya)", ru: "Ортопедическая стоматология (протезирование)" },
  { code: "394607009", uz: "Bolalar stomatologiyasi", ru: "Детская стоматология" },
];

/** Viloyat kodi bo'yicha tumanlar. */
export const districtsOfState = (stateCode: string): DhpCode[] =>
  stateCode ? DHP_DISTRICTS.filter(d => d.code.startsWith(stateCode)) : [];

/** Tuman kodidan viloyat kodini olish (birinchi 4 raqam). */
export const stateOfDistrict = (districtCode: string): string => districtCode.slice(0, 4);
