/**
 * Landing sahifasining BARCHA matnlari — o'zbekcha va ruscha.
 *
 * Nega app'ning umumiy `i18n/translations.ts` fayliga qo'shilmadi:
 * marketing matni strukturali (massivlar, savol-javob juftliklari, tarif
 * ro'yxatlari, interpolyatsiya funksiyalari). U yerdagi tekis
 * `'kalit': 'matn'` xaritasi bunga mos kelmaydi. Bu yerda esa
 * `const ru: LandingCopy` yozuvi tufayli TypeScript ikki tilning
 * to'liq mosligini kompilyatsiya vaqtida tekshiradi — kalit tushib
 * qolsa yoki funksiya imzosi farq qilsa, build yiqiladi.
 */
import type { Language } from '../../context/LanguageContext';

/** Bo'sh qiymatlar render qilinmaydi — egasi keyin to'ldiradi. */
export const LANDING_CONST = {
  phone: "+998 90 824 29 92",
  phoneHref: "tel:+998908242992",
  siteUrl: "https://dentacrm.uz",
  telegram: "https://t.me/dentacrm",
  instagram: "https://www.instagram.com/denta_crm/",
  email: "",
  workHours: "",
  address: "",
};

const uz = {
  meta: {
    title: "DentaCRM — Stomatologiya klinikalari uchun CRM tizimi",
  },

  nav: {
    links: [
      { id: "features",       label: "Imkoniyatlar" },
      { id: "showcase",       label: "Mahsulot" },
      { id: "demo-dashboard", label: "Demo" },
      { id: "ai",             label: "DentaAI" },
      { id: "pricing",        label: "Tariflar" },
      { id: "faq",            label: "Savol-javob" },
    ],
    login: "Tizimga kirish",
    menuOpen: "Menyuni ochish",
    menuClose: "Menyuni yopish",
    langLabel: "Sahifa tili",
  },

  hero: {
    badge: "O'zbekiston stomatologiyalari uchun CRM",
    titleBefore: "Klinikangizni ",
    titleAccent: "aqlli boshqaruv",
    titleAfter: " tizimiga o'tkazing",
    sub: "Bemor kartasi va tish xaritasi, qabullar taqvimi, kassa, SMS va Telegram eslatmalar, DentaAI — hammasi bitta oynada. O'rnatish 1 kun, o'qitish bepul.",
    ctaPrimary: "7 kun bepul sinash",
    ctaSecondary: "Mahsulotni ko'rish",
    micro: ["Kartasiz", "1 kunda o'rnatish", "Istalgan vaqt bekor qilish"],
    stats: [
      { value: 40, suffix: "+",    label: "Faol klinika" },
      { value: 1,  suffix: " kun", label: "O'rnatish muddati" },
      { value: 7,  suffix: " kun", label: "Bepul sinov" },
    ],
    cardSms: "SMS eslatma yuborildi — kelishi tasdiqlandi",
    cardSmsTime: "1 daqiqa oldin",
    cardRevenueLabel: "Bugungi tushum",
    cardRevenueValue: "4.2 mln so'm",
    cardRevenueDelta: "+15%",
    alt: "DentaCRM boshqaruv paneli: kunlik ko'rsatkichlar, daromad grafigi va bugungi qabullar ro'yxati",
  },

  trust: {
    title: "40+ klinika DentaCRM'da ishlaydi",
    clinics: [
      "Asal Dental · Toshkent",
      "Premium Dent · Samarqand",
      "Zamin Stom · Buxoro",
    ],
  },

  showcase: {
    badge: "Mahsulot",
    title: "Bu maket emas — tizimning haqiqiy ekranlari",
    sub: "Quyidagi rasmlar demo ma'lumotlar bilan ishlab turgan tizimdan olingan.",
    phoneAlt: "DentaCRM telefon ekranida",
    phoneTitle: "Telefonda ham xuddi shunday",
    phoneNote: "Brauzerda ochiladi va ilova sifatida o'rnatiladi. Do'kondan yuklab olish shart emas.",
    tabs: [
      {
        id: "dashboard",
        label: "Boshqaruv paneli",
        image: "dashboard",
        alt: "Boshqaruv paneli: kunlik ko'rsatkichlar, daromad grafigi va qabullar",
        bullets: [
          "Kunlik tushum, qabullar va yangi lidlar bitta ekranda",
          "Daromad dinamikasi oylar kesimida",
          "Bugungi jadval — kim, qachon, qaysi shifokorda",
        ],
      },
      {
        id: "tooth-chart",
        label: "Tish xaritasi",
        image: "tooth-chart",
        alt: "Bemor kartasidagi tish xaritasi va davolash rejasi",
        bullets: [
          "Har bir tish uchun holat, tashxis va davolanish tarixi",
          "Davolash rejasi va smeta avtomatik yig'iladi",
          "Bemor kartasida hujjatlar va suratlar saqlanadi",
        ],
      },
      {
        id: "dentaai",
        label: "DentaAI",
        image: "dentaai",
        alt: "DentaAI oynasi: klinika ma'lumotlari bo'yicha savol-javob",
        bullets: [
          "«Bugun nechta qabul bor?» — javob sizning ma'lumotlaringizdan",
          "O'zbek tilida ovozli so'rov",
          "Tayyor savollar bir bosishda",
        ],
      },
      {
        id: "calendar",
        label: "Kalendar",
        image: "calendar",
        alt: "Qabullar taqvimi: shifokorlar bo'yicha kunlik jadval",
        bullets: [
          "Ko'p shifokorli jadval bitta ekranda",
          "Bo'sh vaqtlar va bandlik ko'rinib turadi",
          "Qabulni ko'chirish, bekor qilish va holatini belgilash",
        ],
      },
      {
        id: "finance",
        label: "Moliya",
        image: "finance",
        alt: "Moliya bo'limi: tushum, xarajat va qarzdorlar",
        bullets: [
          "Kassa smenasi va kun yopilishi",
          "Bo'lib to'lash va qarzdorlar ro'yxati",
          "Shifokor ulushi avtomatik hisoblanadi",
        ],
      },
      {
        id: "leads",
        label: "Lidlar",
        image: "leads",
        alt: "Lidlar bo'limi: kanban ustunlari bo'yicha so'rovlar",
        bullets: [
          "Kanban: yangi → bog'landi → yozildi",
          "Biriktirilmagan lidlar alohida ustunda",
          "Tashqi manbalardan API orqali tushadi",
        ],
      },
    ],
  },

  features: {
    badge: "Nega aynan DentaCRM?",
    title: "Hamma narsa — bitta tizimda",
    sub: "Qog'ozbozlik bilan xayrlashing. Klinikangizning har bir bo'limini bitta ekrandan boshqaring.",
    items: [
      { key: "card",     title: "Elektron bemor kartasi",  desc: "To'liq davolanish tarixi, tish xaritasi, hujjatlar va suratlar — xavfsiz bulutda." },
      { key: "calendar", title: "Aqlli qabul va taqvim",   desc: "Ko'p shifokorli vizual jadval. Bandlik va bo'sh vaqtlar bitta ekranda." },
      { key: "sms",      title: "Avtomatik SMS eslatmalar", desc: "Qabul eslatmasi va qayta chaqiruv xabarlari Eskiz orqali avtomatik yuboriladi." },
      { key: "telegram", title: "Telegram bot",            desc: "Klinikangizning shaxsiy boti: navbatga yozilish, eslatma, davolanish tarixi, to'lov cheki." },
      { key: "finance",  title: "Kassa va moliya",         desc: "Smena yopish, bo'lib to'lash, qarzdorlar va shifokor ulushi — bitta joyda." },
      { key: "stock",    title: "Materiallar ombori",      desc: "Muolajaga sarflangan material hisobga olinadi. Kam qolsa — ogohlantirish." },
      { key: "leads",    title: "Lidlar kanbani",          desc: "Reklamadan kelgan so'rovlar yo'qolmaydi: yangi → bog'landi → yozildi." },
      { key: "lab",      title: "Laboratoriya va navbat",  desc: "Lab buyurtmalari va texniklar; qabulxonada navbat ekrani." },
    ],
  },

  demo: {
    badge: "Interaktiv demo",
    title: "O'zingiz bosib ko'ring",
    sub: "Quyidagi panel haqiqiy interfeys asosida tuzilgan — bo'limlarni almashtiring, qidiruvni sinang.",
    urlBar: "app.dentacrm.uz / dashboard",
    clinic: "SmilePro",
    role: "Klinika rahbari",
    sidebarTitle: "Boshqaruv paneli",
    smsPack: "SMS paket xizmati",
    smsPackState: "Faol",
    tabs: {
      dashboard: "Boshqaruv paneli",
      patients: "Bemorlar",
      finances: "Moliya",
      stock: "Materiallar ombori",
    },
    kpi: {
      patients: "Jami bemorlar",
      patientsBadge: "+8 faol",
      appointments: "Bugungi qabullar",
      appointmentsBadge: "4 kutilmoqda",
      revenue: "Oy daromadi",
      revenueBadge: "+12%",
      leads: "Yangi lidlar",
      leadsBadge: "Yangi",
    },
    chartTitle: "Daromad dinamikasi",
    currency: "so'm",
    months: ["Yan", "Fev", "Mar", "Apr", "May", "Iyn", "Iyl", "Avg", "Sen", "Okt", "Noy", "Dek"],
    scheduleTitle: "Bugungi jadval",
    seeAll: "Hammasi",
    status: { done: "Tugallandi", pending: "Kutilmoqda", cancelled: "Bekor" },
    searchPlaceholder: "Bemor ismi yoki telefon...",
    colPatient: "Bemor",
    colPhone: "Telefon",
    colLastVisit: "Oxirgi qabul",
    colDebt: "Qarz",
    colService: "Xizmat",
    colDoctor: "Shifokor",
    colAmount: "Summa",
    colStatus: "Holat",
    debtPaid: "To'liq",
    active: "Faol",
    inactive: "Nofaol",
    finRevenue: "Oy daromadi",
    finExpense: "Xarajat",
    finProfit: "Sof foyda",
    paid: "To'langan",
    unpaid: "Kutilmoqda",
    stockAlert: (n: number) => `Sotib olish buyurtmasi kerak: ${n} ta mahsulot`,
    stockTitle: "Kam qolgan materiallar avtomatik aniqlanadi",
    stockEnough: "Yetarli",
    stockLow: "Kam qoldi",
    stockOut: "Tugamoqda",
    stockMin: "Kamida",
    stockNow: "Hozir",
    unitPcs: "dona",
    services: {
      filling: "Plomba",
      implant: "Implant",
      canal: "Kanal tozalash",
      cleaning: "Tish tozalash",
      braces: "Breket sozlash",
    },
    materials: [
      "Kompozit plomba (Filtek Ultimate)",
      "Anesteziya (Ultracain DS)",
      "Dental implantlar (Osstem)",
      "Sterilizatsiya paketi",
      "Ortodontik yoy (0.16)",
    ],
  },

  toothMap: {
    badge: "Elektron tish xaritasi",
    title: "Interaktiv tish formulasi",
    sub: "Tishni bosing va holatini o'zgartiring — davolash rejasi bilan smeta o'zi yangilanadi.",
    cardTitle: "Tish formula kartasi",
    jawBorder: "JAG' CHEGARASI",
    toothNo: "Tish",
    stateLabel: "Holat:",
    planTitle: "Davolash rejasi",
    planCount: (n: number) => `${n} ta tish`,
    planEmpty: "Barcha tishlar sog'lom. Tishni bosib holatini o'zgartiring.",
    total: "Jami smeta",
    totalNote: "Smeta bemor kartasida saqlanadi va davolash rejasiga bog'lanadi.",
    conditions: {
      healthy:  { label: "Sog'lom",        desc: "Profilaktik ko'rik" },
      cavity:   { label: "Karies",         desc: "Karies davolash" },
      pulpitis: { label: "Kanal (pulpit)", desc: "Kanal tozalash va asab olish" },
      filled:   { label: "Plomba",         desc: "Gelioplastik plomba" },
      crown:    { label: "Toj",            desc: "Metall-keramika toj" },
      missing:  { label: "Yo'q tish",      desc: "Protezlash zarur" },
      implant:  { label: "Implant",        desc: "Dental implant" },
    },
  },

  ai: {
    badge: "DentaAI",
    title: "Klinikangiz haqida so'rang — javob ma'lumotlaringizdan",
    sub: "Tizim ichida DentaAI sizning haqiqiy yozuvlaringiz bilan ishlaydi: yozing yoki o'zbekcha ayting. Quyida ochiq demo versiyasini sinab ko'ring.",
    alt: "DentaAI oynasi: klinika ma'lumotlari bo'yicha savol-javob",
    bullets: [
      "«Bugun nechta qabul bor?», «Kim qarzdor?» — javob yozuvlaringizdan olinadi",
      "O'zbek tilida ovozli so'rov: gapiring, tizim matnga aylantiradi",
      "Tayyor savollar va hisobotlar bir bosishda",
    ],
    pickTopic: "Yo'nalishni tanlang",
    topics: {
      treatment_plan:     "Davolash rejasini tuzish",
      sms_generator:      "SMS va marketing matni",
      staff_optimization: "Klinikani optimallashtirish",
    },
    prompts: {
      treatment_plan:     "Tish muammosi yoki bemor shikoyatini yozing:",
      sms_generator:      "SMS maqsadini yoki aksiyani yozing:",
      staff_optimization: "Klinikadagi qiyinchilikni yozing:",
    },
    samples: {
      treatment_plan:     "35-tishda chuqur karies bor, sovuq va issiqqa og'riydi. Rentgenda ildiz uchi yallig'lanmagan.",
      sms_generator:      "Bemor 3 oydan beri tish tozalash qabuliga kelmadi. Uni bepul profilaktik ko'rikka taklif qilish.",
      staff_optimization: "Klinikamizda 3 ta shifokor ishlaydi, qabul vaqtlari chalkashib ketmoqda, bemorlar 30 daqiqadan ko'p kutmoqda.",
    },
    placeholder: "Bu yerga tafsilotlarni yozing...",
    submit: "DentaAI'ni sinab ko'rish",
    loading: "DentaAI tahlil qilmoqda...",
    answerTitle: "DENTAAI JAVOBI",
    generating: "Javob tayyorlanmoqda...",
    sampleTitle: "NAMUNA JAVOB",
    sampleAnswer:
      "1. Ehtimoliy tashxis: chuqur karies yoki boshlang'ich pulpit.\n" +
      "2. Tavsiya etilgan reja:\n" +
      "   - Anesteziya ostida kariesli to'qimani tozalash.\n" +
      "   - Pulpa holatini tekshirish, zarur bo'lsa kanalni davolash.\n" +
      "   - Muvaqqat plomba, keyin doimiy fotopolimer plomba.\n" +
      "3. Davomiylik: 1-2 seans, har biri 40-50 daqiqa.\n" +
      "4. Profilaktika: kuniga 2 marta tozalash, 6 oyda bir ko'rik.\n\n" +
      "Bu — namuna javob. Yuqoridagi tugmani bosib o'z holatingizni sinab ko'ring.",
    empty: "Yuqoridagi tugmani bosing — bir necha soniyada javob tayyor bo'ladi.",
    ready: "Javob tahrirlash uchun tayyor",
    errors: {
      rateLimit: "Ochiq demo soatiga 5 ta so'rov bilan cheklangan. Tizim ichida chegara ancha yuqori — biroz kutib qayta urinib ko'ring.",
      notConfigured: "AI xizmati hozircha ulanmagan. Iltimos, biz bilan bog'laning.",
      tooShort: "Iltimos, holatni bir oz batafsilroq yozing.",
      generic: "Javob olinmadi. Biroz kutib, qayta urinib ko'ring.",
      network: "Server bilan aloqa o'rnatilmadi. Internetni tekshirib, qayta urinib ko'ring.",
    },
    note: "Zamonaviy til modellari asosida ishlaydi. Ochiq demo cheklangan — to'liq versiya tizim ichida.",
  },

  how: {
    badge: "Qanday boshlanadi",
    title: "3 qadam — va klinika tizimda",
    sub: "Texnik bilim talab qilinmaydi. Qolgan ishni biz bajaramiz.",
    steps: [
      { title: "So'rov qoldiring",   desc: "Formani to'ldiring yoki qo'ng'iroq qiling. 15 daqiqada bog'lanamiz va klinikangizga mos tarifni tanlaymiz." },
      { title: "1 kunda o'rnatamiz", desc: "Shifokorlar, xizmat narxlari va mavjud bemorlar bazasini (Excel yoki qog'oz) biz ko'chiramiz. Telegram bot va SMS ulanadi." },
      { title: "Bepul o'qitamiz",    desc: "Administrator va shifokorlar uchun jonli o'qitish. 7 kun bepul — yoqmasa, hech qanday to'lovsiz to'xtatasiz." },
    ],
    cta: "So'rov qoldirish",
  },

  roi: {
    badge: "Moliyaviy samara kalkulyatori",
    title: "DentaCRM qancha foyda keltiradi?",
    sub: "Klinikangiz o'lchamini kiriting va taxminiy oylik samarani ko'ring.",
    inputsTitle: "Klinika ma'lumotlari",
    doctorsLabel: "Shifokorlar soni:",
    doctorsValue: (n: number) => `${n} ta shifokor`,
    patientsLabel: "Kunlik bemorlar (shifokor boshiga):",
    patientsValue: (n: number) => `${n} ta bemor`,
    note: "Hisob-kitob o'rtacha ko'rsatkichlarga asoslangan taxmin: oyiga 26 ish kuni, o'rtacha chek 300 000 so'm, eslatmasiz kelmaslik 12%. Haqiqiy natija klinikaga qarab farq qiladi.",
    timeTitle: "Tejalgan qog'ozbozlik vaqti",
    timeDesc: "Yozuvlar, hisobotlar va eslatmalarni avtomatlashtirish orqali tejaladigan oylik vaqt.",
    timeUnit: "soat / oy",
    timeSub: (days: number) => `Taxminan ${days} ta to'liq ish kuni`,
    patientsTitle: "Qaytarilgan bemorlar",
    patientsDesc: "Avtomatik SMS va Telegram eslatmalari orqali qaytadigan, aks holda yo'qoladigan bemorlar.",
    patientsUnit: "bemor / oy",
    patientsSub: (sum: string) => `Tushum: +${sum} so'm`,
    totalTitle: "Umumiy qo'shimcha foyda",
    totalDesc: "Qaytarilgan bemorlar va aniq hisob-kitob orqali oyiga hosil bo'ladigan taxminiy qo'shimcha tushum.",
    totalLabel: "har oy qo'shimcha",
    totalCurrency: "so'm",
    timesBadge: (n: number) => `DentaCRM narxidan ~${n} barobar ko'p`,
  },

  compare: {
    badge: "Taqqoslash",
    title: "Qog'oz va Excel'dan DentaCRM'ga",
    sub: "Aslida siz shu uchtasidan birini tanlayapsiz.",
    cols: ["Qog'oz jurnal", "Excel", "DentaCRM"],
    legend: { no: "Yo'q", partial: "Qisman", yes: "Bor" },
    rows: [
      { label: "Bemor kartasi va davolanish tarixi", paper: 1, excel: 1, denta: 2 },
      { label: "Tish xaritasi va davolash rejasi",   paper: 1, excel: 0, denta: 2 },
      { label: "Avtomatik eslatmalar (SMS/Telegram)", paper: 0, excel: 0, denta: 2 },
      { label: "Qarzdorlar nazorati",                 paper: 0, excel: 1, denta: 2 },
      { label: "Shifokor ulushini hisoblash",         paper: 0, excel: 1, denta: 2 },
      { label: "Materiallar sarfi va ombor",          paper: 0, excel: 1, denta: 2 },
      { label: "Bir nechta qurilmadan kirish",        paper: 0, excel: 1, denta: 2 },
      { label: "Rollar bo'yicha kirish cheklovi",     paper: 0, excel: 0, denta: 2 },
      { label: "Tayyor hisobotlar",                   paper: 0, excel: 1, denta: 2 },
      { label: "Ma'lumot bir joyda va yo'qolmaydi",   paper: 0, excel: 1, denta: 2 },
    ],
  },

  integrations: {
    badge: "Integratsiyalar",
    title: "Klinikangiz ishlatadigan xizmatlar bilan bog'langan",
    sub: "Faqat haqiqatda ishlaydigan ulanishlar.",
    items: [
      { key: "telegram", title: "Telegram bot",      desc: "Qabulga yozilish, eslatma, davolanish tarixi, hisob va to'lov cheki, xizmatni baholash. Shifokor va admin uchun kunlik hisobot." },
      { key: "sms",      title: "SMS — Eskiz.uz",    desc: "Klinikangizning Eskiz akkaunti orqali. Shablonlar tizimdan moderatsiyaga yuboriladi." },
      { key: "leads",    title: "Lid manbalari API", desc: "Reklama platformalari va saytdan kelgan so'rovlar API kalit orqali Lidlar bo'limiga tushadi." },
      { key: "dmed",     title: "DMED",              desc: "Sog'liqni saqlash vazirligi tizimi bilan ma'lumot almashinuvi — so'rov bo'yicha ulanadi." },
      { key: "pwa",      title: "Ilova (PWA)",       desc: "Android va iPhone'ga ilova sifatida o'rnatiladi. Do'kondan yuklab olish shart emas." },
      { key: "ai",       title: "DentaAI",           desc: "Tizim ichida savol-javob va o'zbekcha ovozli so'rov. Zamonaviy til modellari asosida." },
    ],
  },

  pricing: {
    badge: "Shaffof tariflar",
    title: "Klinikangiz hajmiga mos to'lov",
    sub: "Yashirin to'lovlar yo'q. Barcha imkoniyatlar har bir tarifda — farq faqat shifokor hisoblari sonida.",
    monthly: "Oylik to'lov",
    annual: "Yillik to'lov",
    saveBadge: "-20%",
    popular: "Tavsiya etiladi",
    perMonth: "so'm / oy",
    annualNote: (sum: string) => `Yiliga ${sum} so'm tejaladi (yillik hisoblanadi)`,
    monthlyNote: "Istalgan vaqtda tarifni o'zgartirish yoki to'xtatish mumkin.",
    seats: (n: number) => (n === 1 ? "1 ta shifokor hisobi" : `${n} tagacha shifokor hisobi`),
    includedTitle: "Hamma tarifda:",
    included: [
      "Bemor kartasi va tish xaritasi",
      "Qabullar taqvimi va navbat",
      "Kassa, qarzdorlar va bo'lib to'lash",
      "Shifokor ulushi hisoboti",
      "Lidlar kanbani",
      "Materiallar ombori",
      "Telegram bot",
      "SMS eslatmalar (Eskiz)",
      "Laboratoriya moduli",
      "DentaAI",
      "Rollar bo'yicha kirish",
      "Tizimni o'rnatib berish va o'qitish",
    ],
    plans: [
      { key: "individual", name: "Individual", desc: "Yakka tartibda ishlaydigan shifokorlar uchun." },
      { key: "start",      name: "Start",      desc: "Kichik va o'rta klinikalar uchun." },
      { key: "pro",        name: "Pro",        desc: "Ko'p shifokorli klinikalar uchun." },
    ],
    cta: "7 kun bepul boshlash",
    ctaNote: "Kartasiz faollashtirish · 7 kunlik to'liq test",
    enterpriseTitle: "10+ shifokor yoki bir nechta filial",
    enterpriseDesc: "Klinikangiz uchun alohida taklif va ko'chirish rejasini tayyorlaymiz.",
    enterpriseCta: "Bog'lanish",
  },

  testimonials: {
    badge: "Mijozlar fikri",
    title: "Stomatologlar biz haqimizda",
    items: [
      { name: "Dr. Sarvar Azimov",   role: "Bosh shifokor, «Asal Dental»",     city: "Toshkent",  initials: "SA", quote: "Shifokorlarning oylik ulushini qo'lda hisoblashga 3 kun ketardi, hozir tizim bir zumda tayyorlab beradi." },
      { name: "Dr. Nargiza Umarova", role: "Ortodont, «Premium Dent»",         city: "Samarqand", initials: "NU", quote: "Telegram bot va SMS eslatmalar tufayli bemorlarning kelmaslik foizi sezilarli kamaydi. Tizim o'zi ishlaydi." },
      { name: "Dr. Elyor Rasulov",   role: "Klinika direktori, «Zamin Stom»",  city: "Buxoro",    initials: "ER", quote: "Tish xaritasini telefonimdan ko'ra olaman. Yangi shifokorlar tizimni atigi bir kunda o'rgandi." },
    ],
  },

  faq: {
    badge: "Savol-javob",
    title: "Ko'p beriladigan savollar",
    sub: "Javobini topa olmadingizmi — qo'ng'iroq qiling, tushuntiramiz.",
    items: [
      {
        q: "Internet uzilib qolsa nima bo'ladi?",
        a: "DentaCRM bulutli tizim: barcha ma'lumot serverda saqlanadi va uzilishda yo'qolmaydi. Internet qaytishi bilan ishni davom ettirasiz. Telefon internetini ulash ham yetarli.",
      },
      {
        q: "Ma'lumotlarim qayerda saqlanadi va qanchalik xavfsiz?",
        a: "Ma'lumotlar bulutdagi PostgreSQL bazasida saqlanadi, aloqa HTTPS orqali shifrlanadi, parollar xeshlangan holda yoziladi. Kirish rollarga bog'liq: masalan, shifokorga moliya bo'limini yopib qo'yish mumkin.",
      },
      {
        q: "7 kunlik bepul sinovdan keyin nima bo'ladi?",
        a: "Sizga mos tarifni tanlab to'laysiz. Sinov davrida kiritilgan ma'lumotlar saqlanib qoladi. To'lamasangiz hisob to'xtatiladi — hech qanday karta yechilmaydi.",
      },
      {
        q: "Eski bemorlar bazasini ko'chirib berasizlarmi?",
        a: "Ha. Excel yoki CSV fayl bo'lsa biz import qilamiz. Qog'oz kartalar bo'lsa, birgalikda kiritish rejasini tuzamiz va yo'l-yo'riq beramiz.",
      },
      {
        q: "Xodimlarni o'qitish qancha vaqt oladi?",
        a: "Administrator uchun odatda 1-2 soat, shifokor uchun yarim soatga yaqin. O'qitish bepul, keyin ham telefon orqali yordam beramiz.",
      },
      {
        q: "To'lovni qanday amalga oshiraman?",
        a: "Naqd, bank o'tkazmasi (shartnoma va hisob-faktura bilan) yoki karta orqali. Oylik yoki yillik to'lash mumkin — yillikda 20% arzon.",
      },
      {
        q: "Istalgan vaqtda to'xtata olamanmi?",
        a: "Ha, majburiyat yo'q. To'xtatganda ma'lumotlaringizni Excel formatida eksport qilib beramiz.",
      },
      {
        q: "Telefonda ishlaydimi?",
        a: "Ha. Brauzerda ochiladi va Android yoki iPhone'ga ilova sifatida o'rnatiladi. Bemorlar uchun esa alohida Telegram bot bor.",
      },
      {
        q: "SMS uchun alohida to'lov bormi?",
        a: "SMS sizning Eskiz.uz akkauntingiz orqali yuboriladi va Eskiz tarifi bo'yicha hisoblanadi. DentaCRM bunga ustama qo'shmaydi.",
      },
      {
        q: "10 tadan ko'p shifokor yoki bir nechta filial bo'lsa-chi?",
        a: "Bog'laning — klinikangiz hajmiga qarab alohida taklif tayyorlaymiz.",
      },
    ],
  },

  cta: {
    title: "Klinikangizni ertagayoq avtomatlashtiring",
    sub: "Ishga tushirish uchun 1 kun kifoya. Ma'lumotlaringizni biz ko'chiramiz, xodimlaringizni bepul o'qitamiz.",
    primary: "7 kun bepul sinash",
    secondary: "Tizimga kirish",
    trust: [
      "Kartasiz ro'yxatdan o'tish",
      "HTTPS shifrlash va rollar bo'yicha kirish",
      "Istalgan vaqtda to'xtatish",
    ],
  },

  footer: {
    desc: "Stomatologiya klinikalari uchun zamonaviy boshqaruv tizimi. Bemorlar, qabullar, moliya, ombor va Telegram bot — hammasi bitta tizimda.",
    product: "Mahsulot",
    company: "Kompaniya",
    contact: "Aloqa",
    privacy: "Maxfiylik siyosati",
    login: "Tizimga kirish",
    telegram: "Telegram",
    instagram: "Instagram",
    rights: "© 2026 DentaCRM.uz — Barcha huquqlar himoyalangan.",
  },

  modal: {
    badge: "DentaCRM · 7 kun bepul",
    title: "Klinikangizni bepul sinab ko'ring",
    sub: "Ma'lumotlaringizni qoldiring — 15 daqiqada bog'lanamiz.",
    name: "Ism-familiya",
    namePlaceholder: "Masalan: Aziz Karimov",
    clinic: "Klinika nomi",
    clinicPlaceholder: "Masalan: Asal Dental yoki Dr. Azimov",
    phone: "Telefon raqam",
    phonePlaceholder: "+998 90 123 45 67",
    city: "Shahar",
    cityOptional: "(ixtiyoriy)",
    cityPlaceholder: "Toshkent, Samarqand, Namangan...",
    doctors: "Shifokorlar soni",
    doctorOptions: [
      { value: 1,  label: "1 ta shifokor" },
      { value: 3,  label: "2-3 ta shifokor" },
      { value: 10, label: "4-10 ta shifokor" },
      { value: 11, label: "10 tadan ko'p" },
    ],
    submit: "7 kunlik bepul sinovni boshlash",
    sending: "Yuborilmoqda...",
    note: "Kredit karta talab etilmaydi · Istalgan vaqt bekor qilish mumkin",
    phoneError: "Telefon raqamni to'liq kiriting: +998 va 9 ta raqam.",
    successTitle: "So'rov qabul qilindi!",
    successBody: (name: string, phone: string) => `${name}, siz bilan ${phone} orqali 15 daqiqada bog'lanamiz.`,
    errorTitle: "Yuborilmadi",
    errorBody: "So'rovni yuborib bo'lmadi. Iltimos, qayta urining yoki bevosita qo'ng'iroq qiling:",
    errorRateLimit: "Bu qurilmadan juda ko'p so'rov yuborildi. Iltimos, bevosita qo'ng'iroq qiling:",
    retry: "Qayta urinish",
    close: "Yopish",
    closeAria: "Oynani yopish",
  },

  sticky: {
    call: "Qo'ng'iroq",
    trial: "7 kun bepul",
  },
};

export type LandingCopy = typeof uz;

const ru: LandingCopy = {
  meta: {
    title: "DentaCRM — CRM-система для стоматологических клиник",
  },

  nav: {
    links: [
      { id: "features",       label: "Возможности" },
      { id: "showcase",       label: "Продукт" },
      { id: "demo-dashboard", label: "Демо" },
      { id: "ai",             label: "DentaAI" },
      { id: "pricing",        label: "Тарифы" },
      { id: "faq",            label: "Вопросы" },
    ],
    login: "Войти в систему",
    menuOpen: "Открыть меню",
    menuClose: "Закрыть меню",
    langLabel: "Язык страницы",
  },

  hero: {
    badge: "CRM для стоматологий Узбекистана",
    titleBefore: "Переведите клинику на ",
    titleAccent: "умное управление",
    titleAfter: "",
    sub: "Карта пациента и зубная формула, расписание приёмов, касса, SMS и Telegram-напоминания, DentaAI — всё в одном окне. Внедрение за 1 день, обучение бесплатно.",
    ctaPrimary: "7 дней бесплатно",
    ctaSecondary: "Посмотреть продукт",
    micro: ["Без карты", "Внедрение за 1 день", "Отмена в любой момент"],
    stats: [
      { value: 40, suffix: "+",     label: "Активных клиник" },
      { value: 1,  suffix: " день", label: "Срок внедрения" },
      { value: 7,  suffix: " дней", label: "Бесплатный период" },
    ],
    cardSms: "SMS-напоминание отправлено — визит подтверждён",
    cardSmsTime: "1 минуту назад",
    cardRevenueLabel: "Выручка за сегодня",
    cardRevenueValue: "4.2 млн сум",
    cardRevenueDelta: "+15%",
    alt: "Панель управления DentaCRM: показатели дня, график выручки и список приёмов",
  },

  trust: {
    title: "40+ клиник работают в DentaCRM",
    clinics: [
      "Asal Dental · Ташкент",
      "Premium Dent · Самарканд",
      "Zamin Stom · Бухара",
    ],
  },

  showcase: {
    badge: "Продукт",
    title: "Это не макет — реальные экраны системы",
    sub: "Скриншоты сделаны в работающей системе на демонстрационных данных.",
    phoneAlt: "DentaCRM на экране телефона",
    phoneTitle: "На телефоне точно так же",
    phoneNote: "Открывается в браузере и устанавливается как приложение. Скачивать из магазина не нужно.",
    tabs: [
      {
        id: "dashboard",
        label: "Панель управления",
        image: "dashboard",
        alt: "Панель управления: показатели дня, график выручки и приёмы",
        bullets: [
          "Выручка, приёмы и новые лиды на одном экране",
          "Динамика дохода по месяцам",
          "Расписание на сегодня — кто, когда и к какому врачу",
        ],
      },
      {
        id: "tooth-chart",
        label: "Зубная карта",
        image: "tooth-chart",
        alt: "Зубная карта и план лечения в карточке пациента",
        bullets: [
          "Состояние, диагноз и история лечения по каждому зубу",
          "План лечения и смета формируются автоматически",
          "Документы и снимки хранятся в карте пациента",
        ],
      },
      {
        id: "dentaai",
        label: "DentaAI",
        image: "dentaai",
        alt: "Окно DentaAI: вопросы по данным клиники",
        bullets: [
          "«Сколько сегодня приёмов?» — ответ из ваших данных",
          "Голосовой запрос на узбекском языке",
          "Готовые вопросы в один клик",
        ],
      },
      {
        id: "calendar",
        label: "Календарь",
        image: "calendar",
        alt: "Расписание приёмов по врачам",
        bullets: [
          "Расписание нескольких врачей на одном экране",
          "Видно свободные окна и загрузку",
          "Перенос, отмена и отметка статуса приёма",
        ],
      },
      {
        id: "finance",
        label: "Финансы",
        image: "finance",
        alt: "Раздел финансов: выручка, расходы и должники",
        bullets: [
          "Кассовая смена и закрытие дня",
          "Рассрочка и список должников",
          "Доля врача считается автоматически",
        ],
      },
      {
        id: "leads",
        label: "Лиды",
        image: "leads",
        alt: "Раздел лидов: заявки по колонкам канбана",
        bullets: [
          "Канбан: новый → связались → записан",
          "Нераспределённые заявки в отдельной колонке",
          "Заявки из внешних источников приходят через API",
        ],
      },
    ],
  },

  features: {
    badge: "Почему DentaCRM?",
    title: "Всё — в одной системе",
    sub: "Попрощайтесь с бумагами. Управляйте каждым отделом клиники с одного экрана.",
    items: [
      { key: "card",     title: "Электронная карта пациента", desc: "Полная история лечения, зубная карта, документы и снимки — в защищённом облаке." },
      { key: "calendar", title: "Умная запись и календарь",   desc: "Наглядное расписание нескольких врачей. Загрузка и свободные окна на одном экране." },
      { key: "sms",      title: "Автоматические SMS",         desc: "Напоминания о приёме и повторные приглашения уходят автоматически через Eskiz." },
      { key: "telegram", title: "Telegram-бот",               desc: "Личный бот клиники: запись, напоминания, история лечения, чек об оплате." },
      { key: "finance",  title: "Касса и финансы",            desc: "Закрытие смены, рассрочка, должники и доля врача — в одном месте." },
      { key: "stock",    title: "Склад материалов",           desc: "Расход материалов учитывается по процедурам. Заканчивается — приходит предупреждение." },
      { key: "leads",    title: "Канбан лидов",               desc: "Заявки из рекламы не теряются: новый → связались → записан." },
      { key: "lab",      title: "Лаборатория и очередь",      desc: "Заказы в лабораторию и техники; экран очереди в холле." },
    ],
  },

  demo: {
    badge: "Интерактивное демо",
    title: "Попробуйте сами",
    sub: "Панель ниже построена на реальном интерфейсе — переключайте разделы, попробуйте поиск.",
    urlBar: "app.dentacrm.uz / dashboard",
    clinic: "SmilePro",
    role: "Руководитель клиники",
    sidebarTitle: "Панель управления",
    smsPack: "SMS-пакет",
    smsPackState: "Активен",
    tabs: {
      dashboard: "Панель управления",
      patients: "Пациенты",
      finances: "Финансы",
      stock: "Склад материалов",
    },
    kpi: {
      patients: "Всего пациентов",
      patientsBadge: "+8 активных",
      appointments: "Приёмов сегодня",
      appointmentsBadge: "4 в ожидании",
      revenue: "Доход за месяц",
      revenueBadge: "+12%",
      leads: "Новые лиды",
      leadsBadge: "Новые",
    },
    chartTitle: "Динамика дохода",
    currency: "сум",
    months: ["Янв", "Фев", "Мар", "Апр", "Май", "Июн", "Июл", "Авг", "Сен", "Окт", "Ноя", "Дек"],
    scheduleTitle: "Расписание на сегодня",
    seeAll: "Все",
    status: { done: "Завершён", pending: "Ожидается", cancelled: "Отменён" },
    searchPlaceholder: "Имя пациента или телефон...",
    colPatient: "Пациент",
    colPhone: "Телефон",
    colLastVisit: "Последний приём",
    colDebt: "Долг",
    colService: "Услуга",
    colDoctor: "Врач",
    colAmount: "Сумма",
    colStatus: "Статус",
    debtPaid: "Оплачено",
    active: "Активен",
    inactive: "Неактивен",
    finRevenue: "Доход за месяц",
    finExpense: "Расходы",
    finProfit: "Чистая прибыль",
    paid: "Оплачено",
    unpaid: "Ожидается",
    stockAlert: (n: number) => `Нужен заказ на закупку: ${n} позиц.`,
    stockTitle: "Заканчивающиеся материалы определяются автоматически",
    stockEnough: "Достаточно",
    stockLow: "Мало",
    stockOut: "Заканчивается",
    stockMin: "Минимум",
    stockNow: "Сейчас",
    unitPcs: "шт",
    services: {
      filling: "Пломба",
      implant: "Имплант",
      canal: "Чистка канала",
      cleaning: "Чистка зубов",
      braces: "Коррекция брекетов",
    },
    materials: [
      "Композитная пломба (Filtek Ultimate)",
      "Анестезия (Ultracain DS)",
      "Дентальные импланты (Osstem)",
      "Пакеты для стерилизации",
      "Ортодонтическая дуга (0.16)",
    ],
  },

  toothMap: {
    badge: "Электронная зубная карта",
    title: "Интерактивная зубная формула",
    sub: "Нажмите на зуб и измените его состояние — план лечения и смета обновятся сами.",
    cardTitle: "Карта зубной формулы",
    jawBorder: "ГРАНИЦА ЧЕЛЮСТЕЙ",
    toothNo: "Зуб",
    stateLabel: "Состояние:",
    planTitle: "План лечения",
    planCount: (n: number) => `${n} зуб.`,
    planEmpty: "Все зубы здоровы. Нажмите на зуб, чтобы изменить состояние.",
    total: "Итого смета",
    totalNote: "Смета сохраняется в карте пациента и связывается с планом лечения.",
    conditions: {
      healthy:  { label: "Здоровый",        desc: "Профилактический осмотр" },
      cavity:   { label: "Кариес",          desc: "Лечение кариеса" },
      pulpitis: { label: "Канал (пульпит)", desc: "Чистка канала и удаление нерва" },
      filled:   { label: "Пломба",          desc: "Светоотверждаемая пломба" },
      crown:    { label: "Коронка",         desc: "Металлокерамическая коронка" },
      missing:  { label: "Отсутствует",     desc: "Требуется протезирование" },
      implant:  { label: "Имплант",         desc: "Дентальный имплант" },
    },
  },

  ai: {
    badge: "DentaAI",
    title: "Спросите о своей клинике — ответ из ваших данных",
    sub: "Внутри системы DentaAI работает с вашими реальными записями: напишите или скажите голосом. Ниже — открытая демоверсия.",
    alt: "Окно DentaAI: вопросы по данным клиники",
    bullets: [
      "«Сколько сегодня приёмов?», «Кто должен?» — ответ берётся из ваших записей",
      "Голосовой запрос на узбекском: говорите, система переводит в текст",
      "Готовые вопросы и отчёты в один клик",
    ],
    pickTopic: "Выберите направление",
    topics: {
      treatment_plan:     "Составить план лечения",
      sms_generator:      "Текст SMS и рассылки",
      staff_optimization: "Оптимизация клиники",
    },
    prompts: {
      treatment_plan:     "Опишите проблему зуба или жалобу пациента:",
      sms_generator:      "Опишите цель SMS или акцию:",
      staff_optimization: "Опишите сложность в работе клиники:",
    },
    samples: {
      treatment_plan:     "На 35-м зубе глубокий кариес, болит от холодного и горячего. На снимке верхушка корня без воспаления.",
      sms_generator:      "Пациент 3 месяца не приходил на чистку зубов. Пригласить его на бесплатный профилактический осмотр.",
      staff_optimization: "В клинике работают 3 врача, время приёмов путается, пациенты ждут больше 30 минут.",
    },
    placeholder: "Опишите детали здесь...",
    submit: "Попробовать DentaAI",
    loading: "DentaAI анализирует...",
    answerTitle: "ОТВЕТ DENTAAI",
    generating: "Готовим ответ...",
    sampleTitle: "ПРИМЕР ОТВЕТА",
    sampleAnswer:
      "1. Вероятный диагноз: глубокий кариес или начальный пульпит.\n" +
      "2. Рекомендуемый план:\n" +
      "   - Удаление поражённых тканей под анестезией.\n" +
      "   - Проверка состояния пульпы, при необходимости лечение канала.\n" +
      "   - Временная пломба, затем постоянная фотополимерная.\n" +
      "3. Длительность: 1-2 визита по 40-50 минут.\n" +
      "4. Профилактика: чистка 2 раза в день, осмотр раз в 6 месяцев.\n\n" +
      "Это пример ответа. Нажмите кнопку выше и проверьте на своём случае.",
    empty: "Нажмите кнопку выше — ответ будет готов за несколько секунд.",
    ready: "Ответ готов к редактированию",
    errors: {
      rateLimit: "Открытое демо ограничено 5 запросами в час. Внутри системы лимит значительно выше — подождите немного и попробуйте снова.",
      notConfigured: "Сервис ИИ пока не подключён. Пожалуйста, свяжитесь с нами.",
      tooShort: "Пожалуйста, опишите ситуацию чуть подробнее.",
      generic: "Ответ не получен. Подождите немного и попробуйте снова.",
      network: "Не удалось связаться с сервером. Проверьте интернет и повторите попытку.",
    },
    note: "Работает на современных языковых моделях. Открытое демо ограничено — полная версия доступна внутри системы.",
  },

  how: {
    badge: "С чего начать",
    title: "3 шага — и клиника в системе",
    sub: "Технических знаний не требуется. Остальное сделаем мы.",
    steps: [
      { title: "Оставьте заявку",   desc: "Заполните форму или позвоните. Свяжемся за 15 минут и подберём тариф под вашу клинику." },
      { title: "Внедрим за 1 день", desc: "Врачей, цены на услуги и текущую базу пациентов (Excel или бумага) перенесём мы. Подключим Telegram-бота и SMS." },
      { title: "Обучим бесплатно",  desc: "Живое обучение для администратора и врачей. 7 дней бесплатно — не понравится, остановитесь без оплаты." },
    ],
    cta: "Оставить заявку",
  },

  roi: {
    badge: "Калькулятор эффекта",
    title: "Сколько выгоды принесёт DentaCRM?",
    sub: "Укажите размер клиники и посмотрите примерный эффект за месяц.",
    inputsTitle: "Данные клиники",
    doctorsLabel: "Количество врачей:",
    doctorsValue: (n: number) => `${n} врач.`,
    patientsLabel: "Пациентов в день (на врача):",
    patientsValue: (n: number) => `${n} пациент.`,
    note: "Расчёт — оценка по средним показателям: 26 рабочих дней в месяц, средний чек 300 000 сум, неявка без напоминаний 12%. Реальный результат зависит от клиники.",
    timeTitle: "Сэкономленное время на бумагах",
    timeDesc: "Время в месяц, которое экономится за счёт автоматизации записей, отчётов и напоминаний.",
    timeUnit: "часов / мес",
    timeSub: (days: number) => `Примерно ${days} полных рабочих дней`,
    patientsTitle: "Возвращённые пациенты",
    patientsDesc: "Пациенты, которые возвращаются благодаря автоматическим SMS и Telegram-напоминаниям.",
    patientsUnit: "пациентов / мес",
    patientsSub: (sum: string) => `Выручка: +${sum} сум`,
    totalTitle: "Общая дополнительная выгода",
    totalDesc: "Примерная дополнительная выручка в месяц за счёт возвращённых пациентов и точного учёта.",
    totalLabel: "дополнительно каждый месяц",
    totalCurrency: "сум",
    timesBadge: (n: number) => `Примерно в ${n} раз больше стоимости DentaCRM`,
  },

  compare: {
    badge: "Сравнение",
    title: "От бумаги и Excel к DentaCRM",
    sub: "По сути вы выбираете один из этих трёх вариантов.",
    cols: ["Бумажный журнал", "Excel", "DentaCRM"],
    legend: { no: "Нет", partial: "Частично", yes: "Есть" },
    rows: [
      { label: "Карта пациента и история лечения",    paper: 1, excel: 1, denta: 2 },
      { label: "Зубная карта и план лечения",         paper: 1, excel: 0, denta: 2 },
      { label: "Автоматические напоминания",          paper: 0, excel: 0, denta: 2 },
      { label: "Контроль должников",                  paper: 0, excel: 1, denta: 2 },
      { label: "Расчёт доли врача",                   paper: 0, excel: 1, denta: 2 },
      { label: "Расход материалов и склад",           paper: 0, excel: 1, denta: 2 },
      { label: "Доступ с нескольких устройств",       paper: 0, excel: 1, denta: 2 },
      { label: "Ограничение доступа по ролям",        paper: 0, excel: 0, denta: 2 },
      { label: "Готовые отчёты",                      paper: 0, excel: 1, denta: 2 },
      { label: "Данные в одном месте и не теряются",  paper: 0, excel: 1, denta: 2 },
    ],
  },

  integrations: {
    badge: "Интеграции",
    title: "Связано с сервисами, которыми пользуется клиника",
    sub: "Только реально работающие подключения.",
    items: [
      { key: "telegram", title: "Telegram-бот",         desc: "Запись на приём, напоминания, история лечения, счёт и чек об оплате, оценка услуги. Ежедневный отчёт врачу и администратору." },
      { key: "sms",      title: "SMS — Eskiz.uz",       desc: "Через аккаунт Eskiz вашей клиники. Шаблоны отправляются на модерацию из системы." },
      { key: "leads",    title: "API источников лидов", desc: "Заявки с рекламных площадок и сайта попадают в раздел «Лиды» по API-ключу." },
      { key: "dmed",     title: "DMED",                 desc: "Обмен данными с системой Минздрава — подключается по запросу." },
      { key: "pwa",      title: "Приложение (PWA)",     desc: "Устанавливается как приложение на Android и iPhone. Скачивать из магазина не нужно." },
      { key: "ai",       title: "DentaAI",              desc: "Вопросы и голосовой запрос на узбекском внутри системы. На современных языковых моделях." },
    ],
  },

  pricing: {
    badge: "Прозрачные тарифы",
    title: "Оплата под размер вашей клиники",
    sub: "Скрытых платежей нет. Все возможности входят в каждый тариф — отличается только число учётных записей врачей.",
    monthly: "Помесячно",
    annual: "На год",
    saveBadge: "-20%",
    popular: "Рекомендуем",
    perMonth: "сум / мес",
    annualNote: (sum: string) => `Экономия ${sum} сум в год (оплата за год)`,
    monthlyNote: "Тариф можно изменить или остановить в любой момент.",
    seats: (n: number) => (n === 1 ? "1 учётная запись врача" : `до ${n} учётных записей врачей`),
    includedTitle: "В каждом тарифе:",
    included: [
      "Карта пациента и зубная карта",
      "Расписание приёмов и очередь",
      "Касса, должники и рассрочка",
      "Отчёт по доле врача",
      "Канбан лидов",
      "Склад материалов",
      "Telegram-бот",
      "SMS-напоминания (Eskiz)",
      "Модуль лаборатории",
      "DentaAI",
      "Доступ по ролям",
      "Внедрение системы и обучение",
    ],
    plans: [
      { key: "individual", name: "Individual", desc: "Для врачей, работающих самостоятельно." },
      { key: "start",      name: "Start",      desc: "Для небольших и средних клиник." },
      { key: "pro",        name: "Pro",        desc: "Для клиник с несколькими врачами." },
    ],
    cta: "Начать 7 дней бесплатно",
    ctaNote: "Активация без карты · Полный доступ на 7 дней",
    enterpriseTitle: "Более 10 врачей или несколько филиалов",
    enterpriseDesc: "Подготовим отдельное предложение и план переноса данных для вашей клиники.",
    enterpriseCta: "Связаться",
  },

  testimonials: {
    badge: "Отзывы клиентов",
    title: "Что говорят стоматологи",
    items: [
      { name: "Др. Сарвар Азимов",   role: "Главный врач, «Asal Dental»",    city: "Ташкент",   initials: "СА", quote: "На ручной расчёт доли врачей за месяц уходило 3 дня, теперь система готовит его мгновенно." },
      { name: "Др. Наргиза Умарова", role: "Ортодонт, «Premium Dent»",       city: "Самарканд", initials: "НУ", quote: "Благодаря Telegram-боту и SMS-напоминаниям процент неявок заметно снизился. Система работает сама." },
      { name: "Др. Эльёр Расулов",   role: "Директор клиники, «Zamin Stom»", city: "Бухара",    initials: "ЭР", quote: "Зубную карту вижу с телефона. Новые врачи освоили систему всего за один день." },
    ],
  },

  faq: {
    badge: "Вопросы и ответы",
    title: "Частые вопросы",
    sub: "Не нашли ответ — позвоните, всё объясним.",
    items: [
      {
        q: "Что будет, если пропадёт интернет?",
        a: "DentaCRM — облачная система: все данные хранятся на сервере и при обрыве связи не теряются. Как только интернет вернётся, вы продолжите работу. Достаточно даже мобильного интернета.",
      },
      {
        q: "Где хранятся мои данные и насколько это безопасно?",
        a: "Данные хранятся в облачной базе PostgreSQL, соединение шифруется по HTTPS, пароли хранятся в виде хешей. Доступ зависит от роли: например, врачу можно закрыть раздел финансов.",
      },
      {
        q: "Что происходит после 7 бесплатных дней?",
        a: "Вы выбираете подходящий тариф и оплачиваете его. Данные, внесённые за пробный период, сохраняются. Если не оплатить — доступ приостанавливается, никакие деньги с карты не списываются.",
      },
      {
        q: "Перенесёте ли вы старую базу пациентов?",
        a: "Да. Если есть файл Excel или CSV — импортируем его. Если карты бумажные, вместе составим план ввода и подскажем, как это сделать быстрее.",
      },
      {
        q: "Сколько времени занимает обучение сотрудников?",
        a: "Администратору обычно нужно 1-2 часа, врачу — около получаса. Обучение бесплатное, дальше помогаем по телефону.",
      },
      {
        q: "Как происходит оплата?",
        a: "Наличными, банковским переводом (с договором и счёт-фактурой) или картой. Можно платить помесячно или за год — при оплате за год на 20% дешевле.",
      },
      {
        q: "Могу ли я остановиться в любой момент?",
        a: "Да, никаких обязательств. При остановке выгрузим ваши данные в формате Excel.",
      },
      {
        q: "Работает ли на телефоне?",
        a: "Да. Открывается в браузере и устанавливается как приложение на Android или iPhone. Для пациентов есть отдельный Telegram-бот.",
      },
      {
        q: "Нужно ли платить за SMS отдельно?",
        a: "SMS отправляются через ваш аккаунт Eskiz.uz и оплачиваются по тарифу Eskiz. DentaCRM наценку не берёт.",
      },
      {
        q: "А если врачей больше 10 или несколько филиалов?",
        a: "Свяжитесь с нами — подготовим отдельное предложение под размер вашей клиники.",
      },
    ],
  },

  cta: {
    title: "Автоматизируйте клинику уже завтра",
    sub: "Для запуска достаточно 1 дня. Данные перенесём мы, сотрудников обучим бесплатно.",
    primary: "7 дней бесплатно",
    secondary: "Войти в систему",
    trust: [
      "Регистрация без карты",
      "HTTPS-шифрование и доступ по ролям",
      "Остановка в любой момент",
    ],
  },

  footer: {
    desc: "Современная система управления для стоматологических клиник. Пациенты, приёмы, финансы, склад и Telegram-бот — всё в одной системе.",
    product: "Продукт",
    company: "Компания",
    contact: "Контакты",
    privacy: "Политика конфиденциальности",
    login: "Войти в систему",
    telegram: "Telegram",
    instagram: "Instagram",
    rights: "© 2026 DentaCRM.uz — Все права защищены.",
  },

  modal: {
    badge: "DentaCRM · 7 дней бесплатно",
    title: "Попробуйте бесплатно в своей клинике",
    sub: "Оставьте данные — свяжемся за 15 минут.",
    name: "Имя и фамилия",
    namePlaceholder: "Например: Азиз Каримов",
    clinic: "Название клиники",
    clinicPlaceholder: "Например: Asal Dental или Др. Азимов",
    phone: "Номер телефона",
    phonePlaceholder: "+998 90 123 45 67",
    city: "Город",
    cityOptional: "(необязательно)",
    cityPlaceholder: "Ташкент, Самарканд, Наманган...",
    doctors: "Количество врачей",
    doctorOptions: [
      { value: 1,  label: "1 врач" },
      { value: 3,  label: "2-3 врача" },
      { value: 10, label: "4-10 врачей" },
      { value: 11, label: "Более 10" },
    ],
    submit: "Начать 7 бесплатных дней",
    sending: "Отправляем...",
    note: "Кредитная карта не требуется · Отмена в любой момент",
    phoneError: "Введите номер полностью: +998 и 9 цифр.",
    successTitle: "Заявка принята!",
    successBody: (name: string, phone: string) => `${name}, свяжемся с вами по номеру ${phone} в течение 15 минут.`,
    errorTitle: "Не отправлено",
    errorBody: "Не удалось отправить заявку. Попробуйте ещё раз или позвоните напрямую:",
    errorRateLimit: "С этого устройства отправлено слишком много заявок. Пожалуйста, позвоните напрямую:",
    retry: "Попробовать снова",
    close: "Закрыть",
    closeAria: "Закрыть окно",
  },

  sticky: {
    call: "Позвонить",
    trial: "7 дней бесплатно",
  },
};

export const content: Record<Language, LandingCopy> = { uz, ru };
